Dev into main (#8)
* no message

* no message

* no message

* no message

* no message

* no message

* no message

* no message

* no message

* no message

* no message

* no message

* no message

diff --git a/.github/workflows/infrastructure.yaml b/.github/workflows/infrastructure.yaml
--- a/.github/workflows/infrastructure.yaml
+++ b/.github/workflows/infrastructure.yaml
@@ -21,6 +21,8 @@ env:
   AZ_MAIN_STATE_FILE_KEY: "main.terraform.tfstate"
   AZ_OWNER_OBJECT_ID: ${{ secrets.AZ_OWNER_OBJECT_ID }}
 
+  GH_TOKEN: ${{ secrets.ANTISPAM_GITHUB_TOKEN }}
+
 jobs:
   openaiservices-infrastructure:
     environment: dev
@@ -103,8 +105,10 @@ jobs:
         run: |
           RESOURCE_GROUP_NAME=$(terraform output -raw resource_group_name)
           FUNCTION_APP_NAME=$(terraform output -raw functionapp_name)
-          curl -X POST \
-            -H "Accept: application/vnd.github.v3+json" \
-            -H "Authorization: token ${{ secrets.ANTISPAM_GITHUB_TOKEN }}" \
-            https://api.github.com/repos/${{ github.repository }}/dispatches \
-            -d '{"event_type":"trigger-deploy-workflow","client_payload":{"resource_group_name":"'"$RESOURCE_GROUP_NAME"'","function_app_name":"'"$FUNCTION_APP_NAME"'"}}'
+
+          if [ -z "$RESOURCE_GROUP_NAME" ] || [ -z "$FUNCTION_APP_NAME" ]; then
+            echo "Error: RESOURCE_GROUP_NAME or FUNCTION_APP_NAME is empty."
+            exit 1
+          fi
+
+          gh workflow run deploy.yaml --ref "${{ github.ref }}" -f resource_group_name="$RESOURCE_GROUP_NAME" -f function_app_name="$FUNCTION_APP_NAME"
