no message

diff --git a/.github/workflows/main-infrastructure.yaml b/.github/workflows/main-infrastructure.yaml
--- a/.github/workflows/main-infrastructure.yaml
+++ b/.github/workflows/main-infrastructure.yaml
@@ -17,68 +17,68 @@ env:
 
 jobs:
   main-infrastructure:
-  environment: ${{ inputs.environment }}
-  runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
+    runs-on: ubuntu-latest
 
-  defaults:
-    run:
-      working-directory: src/infrastructure
+    defaults:
+      run:
+        working-directory: src/infrastructure
 
-  steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Verify Inputs
-      run: |
-        allowed_environments=("dev" "prod")
-        if [[ ! " ${allowed_environments[@]} " =~ " ${{ inputs.environment }} " ]]; then
-          echo "Invalid environment: ${{ inputs.environment }}. Allowed values are: ${allowed_environments[@]}"
-          exit 1
-        fi
+      - name: Verify Inputs
+        run: |
+          allowed_environments=("dev" "prod")
+          if [[ ! " ${allowed_environments[@]} " =~ " ${{ inputs.environment }} " ]]; then
+            echo "Invalid environment: ${{ inputs.environment }}. Allowed values are: ${allowed_environments[@]}"
+            exit 1
+          fi
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
-      with:
-        terraform_wrapper: false
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_wrapper: false
 
-    - name: Terraform Init
-      env:
-        # backend configuration
-        AZ_TERRAFORM_BACKEND_STORAGEACCOUNT: ${{ vars.AZ_TERRAFORM_BACKEND_STORAGEACCOUNT }}
-        AZ_TERRAFORM_BACKEND_RESOURCEGROUP: ${{ vars.AZ_TERRAFORM_BACKEND_RESOURCEGROUP }}
-        AZ_BACKEND_CONTAINER_NAME: ${{ inputs.environment }}
-        AZ_MAIN_STATE_FILE_KEY: "main.terraform.tfstate"
-      run: |
-        terraform init \
-          -backend-config="storage_account_name=${AZ_TERRAFORM_BACKEND_STORAGEACCOUNT}"  \
-          -backend-config="container_name=${AZ_BACKEND_CONTAINER_NAME}" \
-          -backend-config="key=${AZ_MAIN_STATE_FILE_KEY}" \
-          -backend-config="resource_group_name=${AZ_TERRAFORM_BACKEND_RESOURCEGROUP}" \
+      - name: Terraform Init
+        env:
+          # backend configuration
+          AZ_TERRAFORM_BACKEND_STORAGEACCOUNT: ${{ vars.AZ_TERRAFORM_BACKEND_STORAGEACCOUNT }}
+          AZ_TERRAFORM_BACKEND_RESOURCEGROUP: ${{ vars.AZ_TERRAFORM_BACKEND_RESOURCEGROUP }}
+          AZ_BACKEND_CONTAINER_NAME: ${{ inputs.environment }}
+          AZ_MAIN_STATE_FILE_KEY: "main.terraform.tfstate"
+        run: |
+          terraform init \
+            -backend-config="storage_account_name=${AZ_TERRAFORM_BACKEND_STORAGEACCOUNT}"  \
+            -backend-config="container_name=${AZ_BACKEND_CONTAINER_NAME}" \
+            -backend-config="key=${AZ_MAIN_STATE_FILE_KEY}" \
+            -backend-config="resource_group_name=${AZ_TERRAFORM_BACKEND_RESOURCEGROUP}" \
 
-    - name: Terraform Plan
-      env:
-        AZ_OWNER_OBJECT_ID: ${{ secrets.AZ_OWNER_OBJECT_ID }}
-        AZ_OPENAI_STATE_FILE_KEY: "openai.terraform.tfstate"
-      run: |
-        terraform plan -out=tfplan -var-file=environments/${{ inputs.environment }}.tfvars \
-          -var="application_owner_object_id=${AZ_OWNER_OBJECT_ID}" \
-          -var="openai_state_storage_account_name=${AZ_TERRAFORM_BACKEND_STORAGEACCOUNT}" \
-          -var="openai_state_container_name=${AZ_BACKEND_CONTAINER_NAME}" \
-          -var="openai_state_resource_group_name=${AZ_TERRAFORM_BACKEND_RESOURCEGROUP}" \
-          -var="openai_state_key=${AZ_OPENAI_STATE_FILE_KEY}" \
-          -var="telegram_bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}" \
-          -var="telegram_bot_secret_header=${{ secrets.TELEGRAM_BOT_SECRET_HEADER }}"
+      - name: Terraform Plan
+        env:
+          AZ_OWNER_OBJECT_ID: ${{ secrets.AZ_OWNER_OBJECT_ID }}
+          AZ_OPENAI_STATE_FILE_KEY: "openai.terraform.tfstate"
+        run: |
+          terraform plan -out=tfplan -var-file=environments/${{ inputs.environment }}.tfvars \
+            -var="application_owner_object_id=${AZ_OWNER_OBJECT_ID}" \
+            -var="openai_state_storage_account_name=${AZ_TERRAFORM_BACKEND_STORAGEACCOUNT}" \
+            -var="openai_state_container_name=${AZ_BACKEND_CONTAINER_NAME}" \
+            -var="openai_state_resource_group_name=${AZ_TERRAFORM_BACKEND_RESOURCEGROUP}" \
+            -var="openai_state_key=${AZ_OPENAI_STATE_FILE_KEY}" \
+            -var="telegram_bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}" \
+            -var="telegram_bot_secret_header=${{ secrets.TELEGRAM_BOT_SECRET_HEADER }}"
 
-    - name: Apply Terraform plan
-      run: terraform apply tfplan
-# - name: Trigger Deploy Workflow
-#   run: |
-#     RESOURCE_GROUP_NAME=$(terraform output -raw resource_group_name)
-#     FUNCTION_APP_NAME=$(terraform output -raw functionapp_name)
+      - name: Apply Terraform plan
+        run: terraform apply tfplan
+#   - name: Trigger Deploy Workflow
+#     run: |
+#       RESOURCE_GROUP_NAME=$(terraform output -raw resource_group_name)
+#       FUNCTION_APP_NAME=$(terraform output -raw functionapp_name)
 
-#     if [ -z "$RESOURCE_GROUP_NAME" ] || [ -z "$FUNCTION_APP_NAME" ]; then
-#       echo "Error: RESOURCE_GROUP_NAME or FUNCTION_APP_NAME is empty."
-#       exit 1
-#     fi
+#       if [ -z "$RESOURCE_GROUP_NAME" ] || [ -z "$FUNCTION_APP_NAME" ]; then
+#         echo "Error: RESOURCE_GROUP_NAME or FUNCTION_APP_NAME is empty."
+#         exit 1
+#       fi
 
-#     gh workflow run deploy.yaml --ref "${{ github.ref }}" -f resource_group_name="$RESOURCE_GROUP_NAME" -f function_app_name="$FUNCTION_APP_NAME"
+#       gh workflow run deploy.yaml --ref "${{ github.ref }}" -f resource_group_name="$RESOURCE_GROUP_NAME" -f function_app_name="$FUNCTION_APP_NAME"
